#!/bin/bash

adb root && sleep 2 && adb remount &&
find -iname *.xmg | xargs -I xxx adb push xxx /data/ &&
find -iname *.ozu | xargs -I xxx adb push xxx /data/ &&
adb shell lota -f /data/*.ozu -d &&
adb shell lota -x /data/*.xmg -d &&
adb shell blake ota_apply_immediate &&
adb shell blake version

