#! /bin/bash

echo "Removing old temp files"
rm -rf ~/Desktop/blake_packed
echo "Creating new temp files"
mkdir ~/Desktop/blake_packed

echo "Pulling libs and APKS from $OUT folder"
cp $OUT/system/vendor/lib/libblake_jni.so ~/Desktop/blake_packed/
cp $OUT/system/vendor/lib/hw/blake.tegra.so ~/Desktop/blake_packed/
cp $OUT/system/app/NvBlakeManager.apk ~/Desktop/blake_packed/
cp $OUT/system/app/BlakePairing.apk ~/Desktop/blake_packed/

echo "Packing the file"
filename=~/Desktop/blake_`date +"%m_%d_%Hpm_%Mmin"`.tar.gz
tar cfvz $filename ~/Desktop/blake_packed

echo "SUCCESS! $filename"
