#! /bin/bash

#function croot() {
#    cd /home/aharijanto/Programming/nodejs/easycommerce-backend
#}

function lproot() {
    cd /home/aharijanto/Programming/nodejs/easycommerce-backend/dropbox/statichost/landingpage
}

function ubkdb() {
  mysql -u root -p ubksystem
}

function mine1() {
  ssh prospector@nusantara-cloud.com -p 3559
}

function mine2() {
  ssh prospector@nusantara-cloud.com -p 4000 
}

function ubk() {
  #ssh ubkadmin@nusantara-cloud.com -p 3401
  ssh ubkadmin@ubksystem.ddns.net -p 8880
}

function setHDMI() {
  xrandr --output HDMI-2 --left-of eDP-1
}

alias copy='xclip -selection clipboard'

source ~/bin/sources/x1_libinput

function filos-croot() {
  cd /home/aharijanto/Programming/nodejs/ncloud-server/dropbox/dynamichost/app_filosedu
}


# WAR for latest version of tmuxinator
# Problem is with ruby gem paths
export GEM_PATH="$GEM_PATH:/usr/lib/ruby/gems/2.5.0"
